hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    global_step: 2
name: fluke.algorithms.scaffold.SCAFFOLD
