hyperparameters:
  client:
    batch_size: 10
    local_epochs: 10
    loss: CrossEntropyLoss
    model: MNIST_2NN
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
    tau: 5
  model: MNIST_2NN_E
  server:
    weighted: false
name: fluke.algorithms.fedrep.FedRep
