hyperparameters:
  client:
    batch_size: 32
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.1
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    global_step: 2
  model: MNIST_2NN
name: fluke.algorithms.scaffold.SCAFFOLD
